name: main
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the source code
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
    
    - name: Drop history of readme.md - will be generated
      run: |
        FILTER_BRANCH_SQUELCH_WARNING=1 git filter-branch --force --index-filter "git rm --ignore-unmatch readme.md" --prune-empty HEAD
    
    - name: Drop the history and recover only the latest versions of cache files
      run: |
        FILTER_BRANCH_SQUELCH_WARNING=1 git filter-branch --force --index-filter "git rm --ignore-unmatch followers.json repositories.json todos.json prs.md issues.md" --prune-empty HEAD
        git checkout origin/main -- followers.json repositories.json todos.json
    
    - name: Run the workflow script using the integration personal access token
      run: |
        npm install
        node test
        node . ${{github.token}}
    
    - name: Commit and force push Git changes back to the workflow repository
      run: |
        set -e
        set -x
        
        # Configure Git for the push from the workflow to the repository
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        # Stage the Git index changes resulting from the CI script
        git add .
        
        # Reset unstaged changes so that Git commit won't fail (e.g.: package-lock.json, temporary files, …)
        git checkout -- .
        
        # Bail if there are no changes to commit and hence no GitHub Pages to build
        if git diff-index --quiet HEAD --; then
          exit
        fi
        
        # Commit the staged changes to the workflow repository
        git commit -m "Generate the profile repository readme" -m "This commit was automatically generated via GitHub Actions"
        
        # Push the commit to the workflow repository using force since we rewrote history
        git push origin HEAD:main --force
